algoritmo "imc"
// Função :
// Autor :
// Data : 28/07/2022
// Seção de Declarações
var
M, A, IMC: real

inicio
EscrevaL( "digite sua Massa (Kg): ")
leia(M)
EscrevaL( "digite sua Altura (m): ")
leia(A)
IMC <- M / (a^2)
escreval ("seu IMC é de: ", IMC:5:2)
SE (imc >= 18.5) e (IMC < 25) entao
escreval (" Parabéns! Você está no seu peso Ideal.")
senao
escreval( "Atenção! Você não está no seu peso ideal")
fimse

fimalgoritmo
