algoritmo "aula3"

var
      nome: Caractere
        idade, dia, S: inteiro
        M: Real
        
inicio

Escreva("digite seu Nome:")
Leia(Nome)
Escreval("muito prazer, ", nome)
Escreval (" Qual a sua idade? ")
Leia (Idade)
Escreval("Qual o dia do seu Nascimento?")
Leia(dia)
     S<- idade+dia
   Escreval9michel("A soma dos algarismos é: " ,s)
   M<- (idade+dia) / 2
   Escreva("A média entre os números é: " , M)




fimalgoritmo
